### PR TITLE
Android per app language

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Implemented #44 

I used the android framework api's directly because of how flutter handles activities I couldn't get the AppCompat to work. `localeManger` could not be found because no `context` or `activity` is available in the AppCompatDelegate. Probably because the ActivityAware methods are called after onCreate so the activity can't be added to AppCompatDelegate

### CODE REVIEW

**Review by NicolaVerbeeck — APPROVED** [review]

**Comment by vanlooverenkoen** [comment]
@magnatronus is it possible to review this pull request?

**Comment by magnatronus** [comment]
@vanlooverenkoen  Hi, is it possible for you to add a small section in the readme to explain the updated functionality available for Android ?

**Comment by vanlooverenkoen** [comment]
Yes I will

**Comment by vanlooverenkoen** [comment]
@magnatronus can you review again?

**Comment by vanlooverenkoen** [comment]
Thanks :) @magnatronus let me know when this is released on pub.dev?

**Comment by magnatronus** [comment]
should be there now v 0.5.3

**Pull request merged**
